apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: sender
data:
  # App config (non-sensitive)
  NODE_ENV: "production"
  PORT: "3010"
  SESSION_STORE: "redis"
  MESSAGE_QUEUE_BACKEND: "redis"
  WORKER_CONCURRENCY: "3"
  REDIS_TTL_SECONDS: "43200"
  REDIS_QR_TTL_SECONDS: "180"
  REDIS_OWNER_TTL_SECONDS: "60"
  REDIS_CANCEL_TTL_SECONDS: "600"
  REDIS_CAMPAIGN_LOCK_TTL: "3600"
  REDIS_EVENTS_TTL_SECONDS: "86400"
  LOG_LEVEL: "info"
  # S3 variables se configuran vía Secret

  # Keycloak (override here if not provided via Secret)
  KEYCLOAK_URL: "https://auth.mindtechpy.net"
  KEYCLOAK_REALM: "message-sender"
  KEYCLOAK_AUDIENCE: "message-sender-api"
